name: qr_menu_laravel_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_vector_icons: ^1.0.0
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0

  # Voice Search
  speech_to_text: ^5.5.0

  # Common packages
  nb_utils: ^4.5.2
  google_fonts: ^3.0.1
  readmore: ^2.1.0
  url_strategy: ^0.2.0
  lottie: ^1.3.0

  # Firebase
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1

  # State Management Technique
  mobx: ^2.0.7+2
  flutter_mobx: ^2.0.6+1

  # QR Create and Scan
  qr_flutter: ^4.0.0
  scan: 1.6.0

  # Used for image save and pick
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  cached_network_image: ^3.2.1
  permission_handler: ^9.2.0
  screenshot: ^1.2.3
  file_picker: ^4.6.0

  #  Used for App sharing,web View
  url_launcher: ^6.1.2
  share_plus: ^4.0.4
  package_info_plus: ^1.4.2
  grouped_list: ^5.1.1
  flutter_custom_tabs: ^1.0.4

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

  #flutter packages pub run build_runner build --delete-conflicting-outputs
  #flutter run -d chrome --web-port 5000

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/flag/
    - images/icons/
    - images/gifs/

